// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Page is the single-page sandbox UI. Datastar (loaded from CDN) drives the
// control buttons; the high-frequency particle frames are consumed by
// sandbox.js over native SSE.
func Page(sessionID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"h-full\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Physics Sandbox · Go + Datastar</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"><script type=\"module\" src=\"https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0-RC.7/bundles/datastar.js\"></script></head><body class=\"h-full bg-zinc-950 text-zinc-200 overflow-hidden\" data-session=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(sessionID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/page.templ`, Line: 16, Col: 89}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><canvas id=\"scene\" class=\"absolute inset-0 h-full w-full touch-none\"></canvas><div class=\"pointer-events-none absolute left-4 top-4 select-none rounded-lg bg-zinc-900/70 px-4 py-3 font-mono text-xs leading-5 backdrop-blur\"><div class=\"mb-1 text-sm font-semibold text-zinc-100\">Physics Sandbox</div><div>fps <span id=\"stat-fps\" class=\"text-emerald-400\">0</span></div><div>particles <span id=\"stat-particles\" class=\"text-emerald-400\">0</span></div><div>users <span id=\"stat-clients\" class=\"text-emerald-400\">0</span></div><div>tick <span id=\"stat-tick\" class=\"text-emerald-400\">0</span> ms</div><div>frame <span id=\"stat-frame\" class=\"text-emerald-400\">0</span> B</div><div>goroutines <span id=\"stat-goroutines\" class=\"text-emerald-400\">0</span></div></div><div class=\"absolute bottom-4 left-1/2 flex -translate-x-1/2 items-center gap-3 rounded-lg bg-zinc-900/70 px-4 py-2 text-xs backdrop-blur\"><label class=\"flex items-center gap-2\"><span class=\"text-zinc-400\">particles</span> <input id=\"count\" type=\"range\" min=\"500\" max=\"20000\" step=\"500\" value=\"5000\" class=\"accent-emerald-400\"> <span id=\"count-label\" class=\"w-12 text-right font-mono text-emerald-400\">5000</span></label> <button data-on-click=\"@post('/reset')\" class=\"rounded bg-emerald-600 px-3 py-1 font-medium text-white hover:bg-emerald-500\">reset</button></div><div class=\"pointer-events-none absolute right-4 top-4 select-none rounded-lg bg-zinc-900/70 px-3 py-2 text-xs text-zinc-400 backdrop-blur\">drag to stir · open more tabs for multiplayer</div><script type=\"module\" src=\"/static/js/sandbox.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
